# Generated by Django 3.1.7 on 2021-03-02 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glimpse', '0003_auto_20201118_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glimpse',
            name='variant',
            field=models.CharField(blank=True, choices=[(None, 'Inherit'), ('badge', 'Badge'), ('card_square', 'Square card'), ('person', 'Person'), ('quote', 'Quote'), ('row_half', 'Half row'), ('row_full', 'Full row')], default=None, help_text='Form factor variant', max_length=50, null=True, verbose_name='Variant'),
        ),
    ]
